# Calcule de Matriciel


In [2]:
from pylab import *
import numpy as np

- Tableau ```` array() ````  <=> Matrice


In [37]:
aDim1 = array([4,7,9])
print(aDim1, type(aDim1)) # Différent d'une liste

aDim2 = array([aDim1, [4,9,0]])
print(aDim2, type(aDim2))

size(aDim2) #Nombre d'éléments dans le tableau
shape(aDim2) # Taille du tableau 
shape(aDim1)

# Produit entre deux matrice
print(aDim1*aDim2)

#Produit matriciel 

matrice1 = array([[1, 2, 3],[4, 5, 6]])

matrice2 = array([[4],[2],[1]])

dot(matrice1, matrice2) # Rappel le produit de deux matrice de taille n * m et m * p donne une matrice de taille n * p 
# Equivalent
matrice1@matrice2







[4 7 9] <class 'numpy.ndarray'>
[[4 7 9]
 [4 9 0]] <class 'numpy.ndarray'>
[[16 49 81]
 [16 63  0]]


array([[11],
       [32]])

In [69]:
matrice = array([[3 for i in range(7)] for k in range(8)] )
print(matrice)




[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [78]:
matrice1 = np.array([[1],[2],[3]])
matrice2 = np.array([[2,3,4],
                     [1,5,6]])
np.dot(matrice2, matrice1)

array([[20],
       [29]])